import type { Stage05ConsoleFixture } from "../features/mission-console/types.ts";

export const stage05ConsoleFixture: Stage05ConsoleFixture = {
  source: {
    snapshot: "fixtures/telemetry/degraded_snapshot.json",
    trends:
      "docs/development/artifacts/stage03-simulation/degraded-eclipse-thermal-comms.csv",
    channels: "fixtures/telemetry/channels.json",
  },
  spacecraftId: "tf-sat-01",
  scenario: "degraded-eclipse-thermal-comms",
  capturedAt: "2026-04-30T15:10:00Z",
  description:
    "Degraded static snapshot showing eclipse power draw, avionics heating, and reduced downlink margin.",
  channels: [
    {
      channelId: "eps.battery_voltage",
      name: "Battery Bus Voltage",
      subsystem: "eps",
      unit: "V",
      precision: 2,
      description: "Main regulated spacecraft battery bus voltage.",
      nominalRange: { min: 28, max: 31.5 },
      warningRange: { min: 26, max: 33 },
      criticalRange: { min: 24, max: 34.5 },
    },
    {
      channelId: "eps.solar_array_current",
      name: "Solar Array Current",
      subsystem: "eps",
      unit: "A",
      precision: 2,
      description: "Combined current from the deployed solar array strings.",
      nominalRange: { min: 6.5, max: 10.5 },
      warningRange: { min: 4, max: 12 },
      criticalRange: { min: 1.5, max: 14 },
    },
    {
      channelId: "thermal.avionics_temp",
      name: "Avionics Bay Temperature",
      subsystem: "thermal",
      unit: "degC",
      precision: 1,
      description:
        "Internal avionics bay temperature near flight computer stack.",
      nominalRange: { min: 18, max: 42 },
      warningRange: { min: 5, max: 55 },
      criticalRange: { min: -10, max: 70 },
    },
    {
      channelId: "thermal.radiator_temp",
      name: "Radiator Panel Temperature",
      subsystem: "thermal",
      unit: "degC",
      precision: 1,
      description:
        "External radiator panel temperature used to judge heat rejection margin.",
      nominalRange: { min: -20, max: 15 },
      warningRange: { min: -35, max: 30 },
      criticalRange: { min: -55, max: 45 },
    },
    {
      channelId: "adcs.reaction_wheel_x_rpm",
      name: "Reaction Wheel X Speed",
      subsystem: "adcs",
      unit: "rpm",
      precision: 0,
      description:
        "X-axis reaction wheel speed for attitude control monitoring.",
      nominalRange: { min: -2200, max: 2200 },
      warningRange: { min: -3600, max: 3600 },
      criticalRange: { min: -5000, max: 5000 },
    },
    {
      channelId: "adcs.bus_quaternion_error_deg",
      name: "Attitude Error",
      subsystem: "adcs",
      unit: "deg",
      precision: 3,
      description:
        "Pointing error between commanded and estimated spacecraft attitude.",
      nominalRange: { min: 0, max: 0.2 },
      warningRange: { min: 0, max: 0.7 },
      criticalRange: { min: 0, max: 2 },
    },
    {
      channelId: "comms.downlink_snr_db",
      name: "Downlink Signal-To-Noise Ratio",
      subsystem: "comms",
      unit: "dB",
      precision: 1,
      description:
        "Estimated S-band downlink margin at the active ground station.",
      nominalRange: { min: 9, max: 18 },
      warningRange: { min: 5, max: 22 },
      criticalRange: { min: 0, max: 26 },
    },
    {
      channelId: "comms.packet_error_rate_pct",
      name: "Packet Error Rate",
      subsystem: "comms",
      unit: "pct",
      precision: 2,
      description:
        "Rolling percentage of malformed or uncorrectable telemetry frames.",
      nominalRange: { min: 0, max: 0.5 },
      warningRange: { min: 0, max: 2 },
      criticalRange: { min: 0, max: 10 },
    },
    {
      channelId: "prop.tank_pressure_kpa",
      name: "Propellant Tank Pressure",
      subsystem: "prop",
      unit: "kPa",
      precision: 1,
      description: "Regulated monopropellant tank pressure.",
      nominalRange: { min: 1800, max: 2200 },
      warningRange: { min: 1600, max: 2400 },
      criticalRange: { min: 1300, max: 2600 },
    },
    {
      channelId: "payload.imager_temp",
      name: "Payload Imager Temperature",
      subsystem: "payload",
      unit: "degC",
      precision: 1,
      description: "Primary imager focal-plane electronics temperature.",
      nominalRange: { min: -5, max: 25 },
      warningRange: { min: -15, max: 35 },
      criticalRange: { min: -30, max: 50 },
    },
  ],
  points: [
    {
      channelId: "eps.battery_voltage",
      timestamp: "2026-04-30T15:10:00Z",
      value: 25.4,
      unit: "V",
      status: "warning",
      quality: "valid",
    },
    {
      channelId: "eps.solar_array_current",
      timestamp: "2026-04-30T15:10:00Z",
      value: 2.8,
      unit: "A",
      status: "warning",
      quality: "valid",
    },
    {
      channelId: "thermal.avionics_temp",
      timestamp: "2026-04-30T15:10:00Z",
      value: 62.8,
      unit: "degC",
      status: "critical",
      quality: "valid",
    },
    {
      channelId: "thermal.radiator_temp",
      timestamp: "2026-04-30T15:10:00Z",
      value: 32.5,
      unit: "degC",
      status: "warning",
      quality: "valid",
    },
    {
      channelId: "adcs.reaction_wheel_x_rpm",
      timestamp: "2026-04-30T15:10:00Z",
      value: 3460,
      unit: "rpm",
      status: "warning",
      quality: "valid",
    },
    {
      channelId: "adcs.bus_quaternion_error_deg",
      timestamp: "2026-04-30T15:10:00Z",
      value: 0.33,
      unit: "deg",
      status: "warning",
      quality: "valid",
    },
    {
      channelId: "comms.downlink_snr_db",
      timestamp: "2026-04-30T15:10:00Z",
      value: 4.1,
      unit: "dB",
      status: "critical",
      quality: "suspect",
    },
    {
      channelId: "comms.packet_error_rate_pct",
      timestamp: "2026-04-30T15:10:00Z",
      value: 2.8,
      unit: "pct",
      status: "warning",
      quality: "suspect",
    },
    {
      channelId: "prop.tank_pressure_kpa",
      timestamp: "2026-04-30T15:10:00Z",
      value: 1998,
      unit: "kPa",
      status: "nominal",
      quality: "valid",
    },
    {
      channelId: "payload.imager_temp",
      timestamp: "2026-04-30T15:10:00Z",
      value: 29.4,
      unit: "degC",
      status: "warning",
      quality: "valid",
    },
  ],
  alerts: [
    {
      alertId: "alert-thermal-avionics-20260430T151000Z",
      channelId: "thermal.avionics_temp",
      severity: "critical",
      state: "active",
      message:
        "Avionics bay temperature is above warning limit and approaching critical thermal margin.",
      recommendedAction:
        "Reduce payload duty cycle and prioritize thermal recovery monitoring.",
    },
    {
      alertId: "alert-comms-snr-20260430T151000Z",
      channelId: "comms.downlink_snr_db",
      severity: "critical",
      state: "active",
      message: "Downlink SNR has dropped below the warning floor during the pass.",
      recommendedAction:
        "Switch to lower-rate telemetry profile and confirm ground-station pointing.",
    },
    {
      alertId: "alert-eps-battery-20260430T151000Z",
      channelId: "eps.battery_voltage",
      severity: "warning",
      state: "active",
      message: "Battery bus voltage is below the nominal operating band.",
      recommendedAction:
        "Track recovery after eclipse exit before enabling nonessential payload loads.",
    },
  ],
  trends: [
    { timestamp: "2026-04-30T16:00:00Z", sample: 0, elapsedSeconds: 0, channelId: "eps.battery_voltage", value: 30.63, status: "nominal" },
    { timestamp: "2026-04-30T16:00:10Z", sample: 1, elapsedSeconds: 10, channelId: "eps.battery_voltage", value: 30.35, status: "nominal" },
    { timestamp: "2026-04-30T16:00:20Z", sample: 2, elapsedSeconds: 20, channelId: "eps.battery_voltage", value: 29.64, status: "nominal" },
    { timestamp: "2026-04-30T16:00:30Z", sample: 3, elapsedSeconds: 30, channelId: "eps.battery_voltage", value: 28.86, status: "nominal" },
    { timestamp: "2026-04-30T16:00:40Z", sample: 4, elapsedSeconds: 40, channelId: "eps.battery_voltage", value: 28.03, status: "nominal" },
    { timestamp: "2026-04-30T16:00:50Z", sample: 5, elapsedSeconds: 50, channelId: "eps.battery_voltage", value: 27.42, status: "warning" },
    { timestamp: "2026-04-30T16:01:00Z", sample: 6, elapsedSeconds: 60, channelId: "eps.battery_voltage", value: 26.82, status: "warning" },
    { timestamp: "2026-04-30T16:01:10Z", sample: 7, elapsedSeconds: 70, channelId: "eps.battery_voltage", value: 26.41, status: "warning" },
    { timestamp: "2026-04-30T16:01:20Z", sample: 8, elapsedSeconds: 80, channelId: "eps.battery_voltage", value: 26.04, status: "warning" },
    { timestamp: "2026-04-30T16:01:30Z", sample: 9, elapsedSeconds: 90, channelId: "eps.battery_voltage", value: 25.7, status: "critical" },
    { timestamp: "2026-04-30T16:01:40Z", sample: 10, elapsedSeconds: 100, channelId: "eps.battery_voltage", value: 25.45, status: "critical" },
    { timestamp: "2026-04-30T16:01:50Z", sample: 11, elapsedSeconds: 110, channelId: "eps.battery_voltage", value: 25.35, status: "critical" },
    { timestamp: "2026-04-30T16:00:00Z", sample: 0, elapsedSeconds: 0, channelId: "thermal.avionics_temp", value: 24.7, status: "nominal" },
    { timestamp: "2026-04-30T16:00:10Z", sample: 1, elapsedSeconds: 10, channelId: "thermal.avionics_temp", value: 28.4, status: "nominal" },
    { timestamp: "2026-04-30T16:00:20Z", sample: 2, elapsedSeconds: 20, channelId: "thermal.avionics_temp", value: 32.9, status: "nominal" },
    { timestamp: "2026-04-30T16:00:30Z", sample: 3, elapsedSeconds: 30, channelId: "thermal.avionics_temp", value: 38.2, status: "nominal" },
    { timestamp: "2026-04-30T16:00:40Z", sample: 4, elapsedSeconds: 40, channelId: "thermal.avionics_temp", value: 43.5, status: "warning" },
    { timestamp: "2026-04-30T16:00:50Z", sample: 5, elapsedSeconds: 50, channelId: "thermal.avionics_temp", value: 48.2, status: "warning" },
    { timestamp: "2026-04-30T16:01:00Z", sample: 6, elapsedSeconds: 60, channelId: "thermal.avionics_temp", value: 51.4, status: "warning" },
    { timestamp: "2026-04-30T16:01:10Z", sample: 7, elapsedSeconds: 70, channelId: "thermal.avionics_temp", value: 54.5, status: "warning" },
    { timestamp: "2026-04-30T16:01:20Z", sample: 8, elapsedSeconds: 80, channelId: "thermal.avionics_temp", value: 57.3, status: "critical" },
    { timestamp: "2026-04-30T16:01:30Z", sample: 9, elapsedSeconds: 90, channelId: "thermal.avionics_temp", value: 59.9, status: "critical" },
    { timestamp: "2026-04-30T16:01:40Z", sample: 10, elapsedSeconds: 100, channelId: "thermal.avionics_temp", value: 62, status: "critical" },
    { timestamp: "2026-04-30T16:01:50Z", sample: 11, elapsedSeconds: 110, channelId: "thermal.avionics_temp", value: 62.8, status: "critical" },
    { timestamp: "2026-04-30T16:00:00Z", sample: 0, elapsedSeconds: 0, channelId: "comms.downlink_snr_db", value: 11.5, status: "nominal" },
    { timestamp: "2026-04-30T16:00:10Z", sample: 1, elapsedSeconds: 10, channelId: "comms.downlink_snr_db", value: 12, status: "nominal" },
    { timestamp: "2026-04-30T16:00:20Z", sample: 2, elapsedSeconds: 20, channelId: "comms.downlink_snr_db", value: 12.6, status: "nominal" },
    { timestamp: "2026-04-30T16:00:30Z", sample: 3, elapsedSeconds: 30, channelId: "comms.downlink_snr_db", value: 12.8, status: "nominal" },
    { timestamp: "2026-04-30T16:00:40Z", sample: 4, elapsedSeconds: 40, channelId: "comms.downlink_snr_db", value: 12, status: "nominal" },
    { timestamp: "2026-04-30T16:00:50Z", sample: 5, elapsedSeconds: 50, channelId: "comms.downlink_snr_db", value: 10.7, status: "nominal" },
    { timestamp: "2026-04-30T16:01:00Z", sample: 6, elapsedSeconds: 60, channelId: "comms.downlink_snr_db", value: 9.2, status: "nominal" },
    { timestamp: "2026-04-30T16:01:10Z", sample: 7, elapsedSeconds: 70, channelId: "comms.downlink_snr_db", value: 7.6, status: "warning" },
    { timestamp: "2026-04-30T16:01:20Z", sample: 8, elapsedSeconds: 80, channelId: "comms.downlink_snr_db", value: 6, status: "warning" },
    { timestamp: "2026-04-30T16:01:30Z", sample: 9, elapsedSeconds: 90, channelId: "comms.downlink_snr_db", value: 4.9, status: "critical" },
    { timestamp: "2026-04-30T16:01:40Z", sample: 10, elapsedSeconds: 100, channelId: "comms.downlink_snr_db", value: 4.3, status: "critical" },
    { timestamp: "2026-04-30T16:01:50Z", sample: 11, elapsedSeconds: 110, channelId: "comms.downlink_snr_db", value: 4.1, status: "critical" },
    { timestamp: "2026-04-30T16:00:00Z", sample: 0, elapsedSeconds: 0, channelId: "comms.packet_error_rate_pct", value: 0.17, status: "nominal" },
    { timestamp: "2026-04-30T16:00:10Z", sample: 1, elapsedSeconds: 10, channelId: "comms.packet_error_rate_pct", value: 0.18, status: "nominal" },
    { timestamp: "2026-04-30T16:00:20Z", sample: 2, elapsedSeconds: 20, channelId: "comms.packet_error_rate_pct", value: 0.35, status: "nominal" },
    { timestamp: "2026-04-30T16:00:30Z", sample: 3, elapsedSeconds: 30, channelId: "comms.packet_error_rate_pct", value: 0.62, status: "warning" },
    { timestamp: "2026-04-30T16:00:40Z", sample: 4, elapsedSeconds: 40, channelId: "comms.packet_error_rate_pct", value: 0.95, status: "warning" },
    { timestamp: "2026-04-30T16:00:50Z", sample: 5, elapsedSeconds: 50, channelId: "comms.packet_error_rate_pct", value: 1.34, status: "warning" },
    { timestamp: "2026-04-30T16:01:00Z", sample: 6, elapsedSeconds: 60, channelId: "comms.packet_error_rate_pct", value: 1.71, status: "warning" },
    { timestamp: "2026-04-30T16:01:10Z", sample: 7, elapsedSeconds: 70, channelId: "comms.packet_error_rate_pct", value: 2.06, status: "critical" },
    { timestamp: "2026-04-30T16:01:20Z", sample: 8, elapsedSeconds: 80, channelId: "comms.packet_error_rate_pct", value: 2.36, status: "critical" },
    { timestamp: "2026-04-30T16:01:30Z", sample: 9, elapsedSeconds: 90, channelId: "comms.packet_error_rate_pct", value: 2.59, status: "critical" },
    { timestamp: "2026-04-30T16:01:40Z", sample: 10, elapsedSeconds: 100, channelId: "comms.packet_error_rate_pct", value: 2.74, status: "critical" },
    { timestamp: "2026-04-30T16:01:50Z", sample: 11, elapsedSeconds: 110, channelId: "comms.packet_error_rate_pct", value: 2.8, status: "critical" },
  ],
};
